name: jsqpro automatic
on: workflow_dispatch
jobs:
  my_first_job:
    name: step-1 automatic
    runs-on: windows-latest
    steps:
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - run: chrome --version
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
      env:
        JSQPRO_EMAIL: ${{ secrets.JSQPRO_EMAIL }}
        JSQPRO_PASSWORD: ${{ secrets.JSQPRO_PASSWORD }}
    - run: npm install
    - run: npm run jsqpro
