name: jsqpro notify
on: workflow_dispatch
jobs:
  notify:
    name: Send email
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      env:
        JSQPRO_EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    - run: yarn
    - run: yarn run notify:jsqpro
