version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/node:14.17
      filters:
        branches:
          only: master
      steps:
        - checkout
        - run: yarn
        - run: yarn run build
