version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/node:14.17
      steps:
        - checkout
        - run: yarn
        - run: yarn run build

workflows:
  version: 2
    jsqpro:
      jobs:
        - build
        filters:
             branches:
               only:
                 - master
