name: jsqpro notify
on: push
jobs:
  notify:
    name: Send message
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn
    - run: yarn run notify:jsqpro --pass="$JSQPRO_EMAIL_PASS" --dd="$JSQPRO_DD_TOKEN"
      env:
        JSQPRO_EMAIL_PASS: ${{secrets.EMAIL_PASS}}
        JSQPRO_DD_TOKEN: ${{secrets.DD_TOKEN}}
