name: jsqpro automatic
on:
  push:
    branches: [ master ]

jobs:
  my_first_job:
    name: step-1 automatic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    - run: chrome --version

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: allenevans/set-env@v2.0.0
      with:
        JSQPRO_PA: ${{secrets.TOKEN}}
    # - uses: mskelton/setup-yarn@v1

    - run: |
        yarn global add pm2
        pm2 -v
        yarn
        pm2 delete all
        yarn start
      env:
        JSQPRO_PA: ${{secrets.TOKEN}}

  # notify:
  #   name: step-2 Send message
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #   - run: yarn
  #   - run: yarn run notify:jsqpro --pass="$JSQPRO_EMAIL_PASS" --dd="$JSQPRO_DD_TOKEN"
  #     env:
  #       JSQPRO_EMAIL_PASS: ${{secrets.EMAIL_PASS}}
  #       JSQPRO_DD_TOKEN: ${{secrets.DD_TOKEN}}
