name: jsqpro notify
on: push
jobs:
  notify:
    name: Send email
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn
      env:
        JSQPRO_EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    - run: yarn run notify:jsqpro --pass=$JSQPRO_EMAIL_PASS
